# Generated by Django 4.0.3 on 2023-08-15 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_alter_channel_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 11, 38, 29, 112097, tzinfo=utc)),
        ),
    ]
